### ISSUE TITLE
Flutterでのグラフ表示の調査

### ISSUE THREAD

**Issue by makky0620** [ajiwai-project/torichu#6]
- [ ] メジャーなグラフのライブラリが何があるかわかること
- [ ] 円グラフが使えること

**Comment by makky0620** [comment]
こんな感じに表示できたら良いかな？

<img width="482" alt="Screenshot 2023-07-21 at 9 31 46" src="https://github.com/ajiwai-project/torichu/assets/7555074/f6456bf7-f538-47ed-aebb-bbb921cc0165">

@ta9ma0k

**Comment by ta9ma0k** [comment]
良さそう

**Comment by makky0620** [comment]
@ta9ma0k 
じゃあ本実装はいるのでクローズします！
